import { COMMAND } from "@components/Main/Terminal/enums"
import { MACHINE_TYPE } from "@modules/state/base/enums"

// CONSTANTS
export const SYMBOLS = [
  "›",
  "»",
  "*",
  "+",
  "‡",
  "†",
  "+",
  "◊",
  "”",
  "%",
  "#",
  "«",
  "¥",
  "?",
  "»",
  "→",
  "√",
]

export const FULL_COMMANDS = [
  COMMAND.SKIP,
  COMMAND.BLINK,
  COMMAND.HELP,
  COMMAND.BUILD,
  COMMAND.DESTROY,
  COMMAND.WIPE,
  COMMAND.CONNECT,
  COMMAND.DISCONNECT,
  COMMAND.RESOLVE,
  COMMAND.TRANSFER,
  COMMAND.ORDER,
  COMMAND.FAIL,
  COMMAND.ATTACH_DEPOT,
  COMMAND.DETACH_DEPOT,
  COMMAND.EMPTY_DEPOT,
  COMMAND.REFILL_DEPOT,
  COMMAND.SHIP,
  COMMAND.GRADUATE,
]

export const NO_INPUT_COMMANDS = [
  COMMAND.BLINK,
  COMMAND.HELP,
  COMMAND.RESOLVE,
  COMMAND.TRANSFER,
  COMMAND.ORDER,
  COMMAND.FAIL,
  COMMAND.SKIP,
  COMMAND.GRADUATE,
  COMMAND.WIPE,
  COMMAND.START,
]

export const SINGLE_INPUT_COMMANDS = [
  COMMAND.BUILD,
  COMMAND.DESTROY,
  COMMAND.EMPTY_DEPOT,
  COMMAND.DETACH_DEPOT,
  COMMAND.REFILL_DEPOT,
  COMMAND.SHIP,
]

export const MULTI_INPUT_COMMANDS = [
  COMMAND.CONNECT,
  COMMAND.DISCONNECT,
  COMMAND.ATTACH_DEPOT,
]

export const COMMANDS_BY_LEVEL: { [level: number]: COMMAND[] } = {
  0: FULL_COMMANDS,
  1: FULL_COMMANDS,
  2: FULL_COMMANDS,
}

export const commandsByTutorialProgress = (level: number) => {
  if (level > 28) {
    return FULL_COMMANDS
  }

  if (level > 18) {
    return [
      COMMAND.BLINK,
      COMMAND.REFILL_DEPOT,
      COMMAND.ATTACH_DEPOT,
      COMMAND.DETACH_DEPOT,
      COMMAND.CONNECT,
      COMMAND.DISCONNECT,
      COMMAND.BUILD,
      COMMAND.DESTROY,
      COMMAND.SHIP,
      COMMAND.HELP,
      COMMAND.GRADUATE
    ]
  }

  if (level > 12) {
    return [
      COMMAND.BLINK,
      COMMAND.REFILL_DEPOT,
      COMMAND.ATTACH_DEPOT,
      COMMAND.DETACH_DEPOT,
      COMMAND.CONNECT,
      COMMAND.DISCONNECT,
      COMMAND.SHIP,
      COMMAND.HELP,
      COMMAND.GRADUATE
    ]
  }

  if (level > 8) {
    return [
      COMMAND.BLINK,
      COMMAND.REFILL_DEPOT,
      COMMAND.ATTACH_DEPOT,
      COMMAND.DETACH_DEPOT,
      COMMAND.CONNECT,
      COMMAND.DISCONNECT,
      COMMAND.HELP,
      COMMAND.GRADUATE
    ]
  }

  if (level > 7) {
    return [
      COMMAND.BLINK,
      COMMAND.REFILL_DEPOT,
      COMMAND.ATTACH_DEPOT,
      COMMAND.DETACH_DEPOT,
      COMMAND.HELP,
      COMMAND.GRADUATE
    ]
  }

  if (level > 6) {
    return [COMMAND.BLINK, COMMAND.REFILL_DEPOT, COMMAND.HELP, COMMAND.GRADUATE]
  }

  if (level > -1) {
    return [COMMAND.BLINK, COMMAND.SKIP, COMMAND.HELP]
  }
}

export const FULL_MACHINES = [
  MACHINE_TYPE.SPLITTER,
  MACHINE_TYPE.MIXER,
  MACHINE_TYPE.DRYER,
  MACHINE_TYPE.BOILER,
  MACHINE_TYPE.CENTRIFUGE,
  MACHINE_TYPE.GRINDER,
  MACHINE_TYPE.RAT_CAGE,
  MACHINE_TYPE.MEALWORM_VAT,
]

export const MACHINES_BY_LEVEL: { [level: number]: MACHINE_TYPE[] } = {
  0: [MACHINE_TYPE.DRYER],
  1: [MACHINE_TYPE.DRYER],
  2: [MACHINE_TYPE.DRYER],
  3: FULL_MACHINES,
}

export const FIXED_MACHINE_TYPES = [
  MACHINE_TYPE.PLAYER,
  MACHINE_TYPE.INLET,
  MACHINE_TYPE.OUTLET,
]
export const BETWEEN_SQUARE_BRACKETS = /(?<=\[).+?(?=\])/g
export const BETWEEN_BRACKETS = /(?<=\().+?(?=\))/g
export const BETWEEN_CARETS = /(?<=\>).+?(?=\<)/g
