// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */
enum ENTITY_TYPE {
  NONE,
  ORDER,
  OFFER,
  POD,
  MACHINE,
  TANK
}

enum MACHINE_TYPE {
  NONE,
  INLET,
  OUTLET,
  PLAYER,
  SPLITTER,
  MIXER,
  DRYER,
  BOILER,
  CENTRIFUGE,
  GRINDER,
  RAT_CAGE,
  MEALWORM_VAT
}

enum PORT_INDEX {
  FIRST,
  SECOND
}

enum MATERIAL_DIFFICULTY {
  NOVICE,
  INTERMEDIATE,
  ADVANCED,
  NIGHTMARE
}
