// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */
enum ENTITY_TYPE {
  NONE,
  LEVEL,
  BOX,
  MACHINE,
  CONNECTION,
  MATERIAL,
  PORT
}

enum MACHINE_TYPE {
  NONE,
  INLET,
  OUTLET,
  CORE,
  BLENDER,
  SPLITTER,
  SCORCHER,
  COMBI_GATE
}

enum MATERIAL_TYPE {
  NONE,
  BUG,
  PISS,
  BLOOD,
  PRIME,
  M150ED,
  BANG,
  MONSTER,
  CLUB_MATE,
  SPRITE,
  MILK,
  JUGGERNOG,
  TABASCO,
  IBUPROFENE,
  AMMONIA,
  NYQUIL
}

enum PORT_TYPE {
  INPUT,
  OUTPUT
}

enum PORT_PLACEMENT {
  TOP,
  RIGHT,
  BOTTOM,
  LEFT
}
