// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { GameConfig, GameConfigData, GameConfigTableId } from "./tables/GameConfig.sol";
import { EntityType, EntityTypeTableId } from "./tables/EntityType.sol";
import { MachineType, MachineTypeTableId } from "./tables/MachineType.sol";
import { MaterialType, MaterialTypeTableId } from "./tables/MaterialType.sol";
import { Amount, AmountTableId } from "./tables/Amount.sol";
import { Name, NameTableId } from "./tables/Name.sol";
import { CarriedBy, CarriedByTableId } from "./tables/CarriedBy.sol";
import { BuildIndex, BuildIndexTableId } from "./tables/BuildIndex.sol";
import { SpawnIndex, SpawnIndexTableId } from "./tables/SpawnIndex.sol";
import { Tutorial, TutorialTableId } from "./tables/Tutorial.sol";
import { TutorialLevel, TutorialLevelTableId } from "./tables/TutorialLevel.sol";
import { TutorialOrders, TutorialOrdersTableId } from "./tables/TutorialOrders.sol";
import { Order, OrderData, OrderTableId } from "./tables/Order.sol";
import { CompletedPlayers, CompletedPlayersTableId } from "./tables/CompletedPlayers.sol";
import { LastResolved, LastResolvedTableId } from "./tables/LastResolved.sol";
import { Input, InputTableId } from "./tables/Input.sol";
import { Output, OutputTableId } from "./tables/Output.sol";
import { IncomingConnections, IncomingConnectionsTableId } from "./tables/IncomingConnections.sol";
import { OutgoingConnections, OutgoingConnectionsTableId } from "./tables/OutgoingConnections.sol";
import { StorageConnection, StorageConnectionTableId } from "./tables/StorageConnection.sol";
import { MachinesInPod, MachinesInPodTableId } from "./tables/MachinesInPod.sol";
import { StorageInPod, StorageInPodTableId } from "./tables/StorageInPod.sol";
import { FixedEntities, FixedEntitiesData, FixedEntitiesTableId } from "./tables/FixedEntities.sol";
import { CurrentOrder, CurrentOrderTableId } from "./tables/CurrentOrder.sol";
import { Recipe, RecipeTableId } from "./tables/Recipe.sol";
