// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { EntityType, EntityTypeTableId } from "./tables/EntityType.sol";
import { MachineType, MachineTypeTableId } from "./tables/MachineType.sol";
import { MaterialType, MaterialTypeTableId } from "./tables/MaterialType.sol";
import { PortType, PortTypeTableId } from "./tables/PortType.sol";
import { Name, NameTableId } from "./tables/Name.sol";
import { Energy, EnergyTableId } from "./tables/Energy.sol";
import { CarriedBy, CarriedByTableId } from "./tables/CarriedBy.sol";
import { CreatedBy, CreatedByTableId } from "./tables/CreatedBy.sol";
import { Amount, AmountTableId } from "./tables/Amount.sol";
import { SourcePort, SourcePortTableId } from "./tables/SourcePort.sol";
import { TargetPort, TargetPortTableId } from "./tables/TargetPort.sol";
import { CreationBlock, CreationBlockTableId } from "./tables/CreationBlock.sol";
import { ReadyBlock, ReadyBlockTableId } from "./tables/ReadyBlock.sol";
import { BuildIndex, BuildIndexTableId } from "./tables/BuildIndex.sol";
import { Level, LevelTableId } from "./tables/Level.sol";
import { LastResolved, LastResolvedTableId } from "./tables/LastResolved.sol";
import { Input, InputTableId } from "./tables/Input.sol";
import { Output, OutputTableId } from "./tables/Output.sol";
import { PerformanceRatings, PerformanceRatingsTableId } from "./tables/PerformanceRatings.sol";
import { CompletionTime, CompletionTimeTableId } from "./tables/CompletionTime.sol";
import { GameConfig, GameConfigData, GameConfigTableId } from "./tables/GameConfig.sol";
