// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Type, TypeTableId } from "./tables/Type.sol";
import { Name, NameTableId } from "./tables/Name.sol";
import { Energy, EnergyTableId } from "./tables/Energy.sol";
import { CreationBlock, CreationBlockTableId } from "./tables/CreationBlock.sol";
import { ReadyBlock, ReadyBlockTableId } from "./tables/ReadyBlock.sol";
import { BodyId, BodyIdTableId } from "./tables/BodyId.sol";
import { Level, LevelTableId } from "./tables/Level.sol";
import { Position, PositionData, PositionTableId } from "./tables/Position.sol";
import { ConnectionCapacity, ConnectionCapacityTableId } from "./tables/ConnectionCapacity.sol";
import { SourceEntity, SourceEntityTableId } from "./tables/SourceEntity.sol";
import { TargetEntity, TargetEntityTableId } from "./tables/TargetEntity.sol";
import { ClaimBlock, ClaimBlockTableId } from "./tables/ClaimBlock.sol";
import { GameConfig, GameConfigData, GameConfigTableId } from "./tables/GameConfig.sol";
