// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */
enum ENTITY_TYPE {
  BOX,
  CORE,
  MACHINE,
  CONNECTION,
  RESOURCE,
  PORT,
  CLAIM
}

enum MACHINE_TYPE {
  BLOCKER,
  SPLITTER,
  COMBINATOR,
  MIXER,
  FILTER,
  SHOWER,
  DRYER,
  HEATER,
  FREEZER,
  GRINDER
}

enum RESOURCE_TYPE {
  PELLET,
  DIRT,
  PISS,
  BLOOD
}

enum CONNECTION_TYPE {
  CONTROL,
  RESOURCE
}

enum PORT_TYPE {
  INPUT,
  OUTPUT
}

enum PORT_PLACEMENT {
  TOP,
  RIGHT,
  BOTTOM,
  LEFT
}

enum ROTATION {
  DEG0,
  DEG90,
  DEG180,
  DEG270
}
