// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */
enum EntityType {
  CORE,
  RESOURCE,
  PORTAL,
  MOVER,
  CONTROL_SPLIT,
  CONVERTER
}

enum ConnectionType {
  RESOURCE,
  CONTROL
}
