// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */
enum EntityType {
  CORE,
  UNTRAVERSABLE,
  CLAIM,
  RESOURCE_CONNECTION,
  CONTROL_CONNECTION,
  RESOURCE,
  RESOURCE_TO_ENERGY
}
