// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { MACHINE_TYPE, ROTATION } from "./../Types.sol";

interface IBuildSystem {
  function mc_BuildSystem_build(
    MACHINE_TYPE _machineType,
    int32 _x,
    int32 _y,
    ROTATION _rotation
  ) external returns (bytes32);
}
