// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { EntityType } from "./../Types.sol";

interface IBuildSystem {
  function mc_BuildSystem_build(EntityType entityType, int32 x, int32 y) external;
}
