// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { EntityType } from "./../Types.sol";
import { PositionData } from "./../Tables.sol";

interface IBuildSystem {
  function mc_BuildSystem_build(
    EntityType _entityType,
    PositionData memory _location
  ) external returns (bytes32 entity);

  function mc_BuildSystem_build(
    EntityType connectionType,
    bytes32 _sourceEntity,
    bytes32 _targetEntity
  ) external returns (bytes32 connectionEntity);

  function mc_BuildSystem_destroy(bytes32 _entity) external;
}
