// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { CONNECTION_TYPE } from "./../common.sol";

interface IConnectionSystem {
  function mc_ConnectionSystem_connect(
    CONNECTION_TYPE _connectionType,
    bytes32 _sourcePort,
    bytes32 _targetPort
  ) external returns (bytes32);

  function mc_ConnectionSystem_disconnect(bytes32 _connectionEntity) external;
}
