// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { PORT_INDEX } from "./../common.sol";

/**
 * @title IConnectSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IConnectSystem {
  function connect(bytes32 _sourceMachine, bytes32 _targetMachine, PORT_INDEX _portIndex) external;
}
