// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IConnectionSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IConnectionSystem {
  function connect(bytes32 _sourcePort, bytes32 _targetPort) external returns (bytes32);

  function disconnect(bytes32 _connectionEntity) external;
}
