// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { ConnectionType } from "./../Types.sol";

interface IConnectSystem {
  function mc_ConnectSystem_connect(ConnectionType connectionType, bytes32 _organEntity) external;

  function mc_ConnectSystem_disconnect(ConnectionType connectionType) external;

  function mc_ConnectSystem_settle() external;
}
