// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ICSplitSystem {
  function mc_CSplitSystem_connect(bytes32 _sourceOrgan, bytes32 _targetOrgan) external;

  function mc_CSplitSystem_disconnect(bytes32 _sourceOrgan) external;
}
