// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { MACHINE_TYPE } from "./../common.sol";

/**
 * @title IDepotSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IDepotSystem {
  function attachDepot(bytes32 _depotEntity, MACHINE_TYPE _machineType) external;

  function detachDepot(MACHINE_TYPE _machineType) external;

  function clearDepot(bytes32 _depotEntity) external;
}
