// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IDepotSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IDepotSystem {
  function attachDepot(bytes32 _depotEntity, bytes32 _targetEntity) external;

  function detachDepot(bytes32 _depotEntity) external;

  function emptyDepot(bytes32 _depotEntity) external;
}
