// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ITankSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ITankSystem {
  function attachTank(bytes32 _tankEntity, bytes32 _targetEntity) external;

  function detachTank(bytes32 _tankEntity) external;

  function emptyTank(bytes32 _tankEntity) external;
}
