// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { MATERIAL_TYPE } from "./../common.sol";

/**
 * @title IDevSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IDevSystem {
  function warp(uint32 _level) external;

  function graduate() external;

  function fillDepot(bytes32 _depotEntity, uint32 _amount, MATERIAL_TYPE _materialType) external;
}
