// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { MaterialId } from "./../../libraries/Libraries.sol";

/**
 * @title IDevSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IDevSystem {
  function graduate() external;

  function fillTank(bytes32 _tankEntity, uint32 _amount, MaterialId _materialId) external;

  function reward() external;

  function charge() external;
}
