// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IDevSystem {
  function mc_DevSystem_set(bytes32 _tableId, bytes32 _entity, bytes memory value) external;

  function mc_DevSystem_set(bytes32 _tableId, bytes32 _entity, int32 x, int32 y) external;
}
