// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { PORT_INDEX } from "./../common.sol";

/**
 * @title IDisconnectSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IDisconnectSystem {
  function disconnect(bytes32 _sourceMachine, PORT_INDEX _portIndex) external;
}
