// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IInit2System
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IInit2System {
  function init2() external;
}
