// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IMoverSystem {
  function mc_MoverSystem_charge(bytes32 _sourceEntity) external;

  function mc_MoverSystem_move(bytes32 _sourceEntity, bytes32 _targetEntity, int32 x, int32 y) external;
}
