// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { MaterialId } from "./../../libraries/Libraries.sol";

/**
 * @title IOrderSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IOrderSystem {
  function createOrder(
    string memory _title,
    MaterialId _materialId,
    uint32 _amount,
    uint32 _reward,
    uint32 _duration,
    uint32 _maxPlayers
  ) external returns (bytes32 orderEntity);

  function cancelOrder(bytes32 _orderEntity) external;

  function acceptOrder(bytes32 _orderEntity) external;

  function unacceptOrder() external;
}
