// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { MATERIAL_TYPE } from "./../common.sol";

/**
 * @title IOrderSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IOrderSystem {
  function createOrder(
    MATERIAL_TYPE _resourceMaterialType,
    uint32 _resourceAmount,
    MATERIAL_TYPE _goalMaterialType,
    uint32 _goalAmount,
    uint32 _reward,
    uint32 _duration,
    uint32 _maxPlayers
  ) external returns (bytes32);

  function ship(bytes32 _depotEntity) external;

  function accept(bytes32 _orderEntity) external;

  function cancel(bytes32 _orderEntity) external;
}
