// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IPortalSystem {
  function mc_PortalSystem_charge(bytes32 _sourceEntity) external;

  function mc_PortalSystem_exit(bytes32 _sourceEntity) external;
}
