// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { ROTATION } from "./../Types.sol";

interface IRotateSystem {
  function mc_RotateSystem_rotate(bytes32 _entity, ROTATION _rotation) external;
}
