// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { MACHINE_TYPE } from "./../common.sol";

/**
 * @title IStorageSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IStorageSystem {
  function connectStorage(bytes32 _storageEntity, MACHINE_TYPE _machineType) external;

  function disconnectStorage(MACHINE_TYPE _machineType) external;

  function clearStorage(bytes32 _storageEntity) external;
}
