// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

interface ITransferSystem {
  function mc_TransferSystem_transfer() external returns (bytes32);
}
