// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IWarpSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IWarpSystem {
  function warp(uint32 _level) external;

  function graduate() external;
}
