// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { IBaseWorld } from "@latticexyz/world/src/codegen/interfaces/IBaseWorld.sol";

import { IWarpSystem } from "./IWarpSystem.sol";
import { IInit2System } from "./IInit2System.sol";
import { IInitSystem } from "./IInitSystem.sol";
import { IBuildSystem } from "./IBuildSystem.sol";
import { IConnectSystem } from "./IConnectSystem.sol";
import { IDestroySystem } from "./IDestroySystem.sol";
import { IDisconnectSystem } from "./IDisconnectSystem.sol";
import { IResolveSystem } from "./IResolveSystem.sol";
import { IOrderSystem } from "./IOrderSystem.sol";
import { IStorageSystem } from "./IStorageSystem.sol";
import { INameSystem } from "./INameSystem.sol";
import { ISpawnSystem } from "./ISpawnSystem.sol";
import { IStartSystem } from "./IStartSystem.sol";

/**
 * @title IWorld
 * @notice This interface integrates all systems and associated function selectors
 * that are dynamically registered in the World during deployment.
 * @dev This is an autogenerated file; do not edit manually.
 */
interface IWorld is
  IBaseWorld,
  IWarpSystem,
  IInit2System,
  IInitSystem,
  IBuildSystem,
  IConnectSystem,
  IDestroySystem,
  IDisconnectSystem,
  IResolveSystem,
  IOrderSystem,
  IStorageSystem,
  INameSystem,
  ISpawnSystem,
  IStartSystem
{

}
